### ISSUE TITLE
Aout direct BCE loss

### ISSUE THREAD

**Issue by jiachunjin** [haoosz/BiGR#2]
Hi, interesting work!
I am wondering why substituting the Bernoulli diffusion process with direct BCE loss hurts the performance, did the loss converge and do you have any further insights on this?
Thanks a lot!

**Comment by haoosz** [comment]
Hi, in our experiment, direct BCE can converge but does not fit well, under which setting the generated images are smooth. We suspect this is because the direct BCE loss is so strict that it can lead to the output codes being close to 1 or 0. This makes the sampling process lack the randomness needed.

We also tried direct L2 loss and found that it performed similarly to direct BCE. Therefore, we choose the Bernoulli diffusion process to model the Bernoulli probability.

Thank you!
